use crate::ui_auditor::{UiAuditCollector, PanelAudit, PanelAuditor};
use bevy::prelude::*;
use bevy_egui::{egui, EguiContexts};
use std::fs;
use std::path::Path;
use egui::text::LayoutJob;
use egui::TextBuffer;
use std::sync::Arc;
use crate::node_graph::{NodeGraph, NodeKind};
use crate::timeline::Timeline;